# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trump2', '0003_auto_20170815_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='pdated',
            new_name='updated',
        ),
    ]
