# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trump2', '0005_auto_20170815_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='updated',
        ),
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateField(help_text='Enter in dd/mm/yyyy format', verbose_name='Date of Last Lesson'),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.DateField(help_text='Enter in dd/mm/yyyy format', verbose_name='Date of First Lesson'),
        ),
    ]
