# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trump2', '0007_course_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='synced',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
