# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trump2', '0008_lesson_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='instructors',
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructors',
            field=models.ManyToManyField(to='trump2.Instructor'),
        ),
    ]
