# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trump2', '0012_auto_20170818_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='moe_expiry',
            field=models.DateField(blank=True, verbose_name='MOE Expiry Date'),
        ),
    ]
