# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trump2', '0014_auto_20170824_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='setlessoninstructors',
            field=models.BooleanField(default=True, verbose_name='Add owner as an instructor for all lessons'),
        ),
    ]
